package lesson3;

public class StringMain {
    public static void main(String[] args) {
        StringMain stringMain = new StringMain();
        int result = stringMain.sumOfTwoNumbers(2, 4);

        System.out.println("Result is: " + result);

        System.out.println(stringMain.getText());


    }

    public int sumOfTwoNumbers (int num1, int num2){
        int result = num1+num2;
        return result;
    }

    public String getText (){
        return  "This text is generated by a robot.";
    }

}
